"""create_arxiv_model

Revision ID: 59d36a382b00
Revises: dfca016e09f5
Create Date: 2024-06-28 20:12:12.348203

"""



# revision identifiers, used by Alembic.
revision = "59d36a382b00"
down_revision = "dfca016e09f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
