"""Migration Test

Revision ID: 6ed92e4e3076
Revises: 213ff64d0e13
Create Date: 2024-06-30 12:54:44.070492

"""



# revision identifiers, used by Alembic.
revision = "6ed92e4e3076"
down_revision = "213ff64d0e13"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
