"""create_arxiv_model

Revision ID: dfca016e09f5
Revises: 1880d5003737
Create Date: 2024-06-28 19:20:16.017755

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "dfca016e09f5"
down_revision = "1880d5003737"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "query_results", "journal", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "query_results", "journal", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
