"""arxiv_model

Revision ID: 1880d5003737
Revises: c79b0938ea4b
Create Date: 2024-06-28 11:51:56.119132

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "1880d5003737"
down_revision = "c79b0938ea4b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "query_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query", sa.String(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("status", sa.Integer(), nullable=False),
        sa.Column("num_results", sa.Integer(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_query_records_query"), "query_records", ["query"], unique=False
    )
    op.create_index(
        op.f("ix_query_records_timestamp"), "query_records", ["timestamp"], unique=False
    )
    op.create_table(
        "query_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("journal", sa.String(), nullable=False),
        sa.Column("query_record_id", sa.Integer(), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "update_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["query_record_id"],
            ["query_records.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("query_results")
    op.drop_index(op.f("ix_query_records_timestamp"), table_name="query_records")
    op.drop_index(op.f("ix_query_records_query"), table_name="query_records")
    op.drop_table("query_records")
    # ### end Alembic commands ###
