"""Migration Test

Revision ID: 63b567c97add
Revises: 43f4943b3209
Create Date: 2024-06-30 14:02:06.992992

"""



# revision identifiers, used by Alembic.
revision = "63b567c97add"
down_revision = "43f4943b3209"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
